/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author seccim
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    
    private TelaLogin tl;
    
    public void setTelaLogin (TelaLogin tl) {
        this.tl = tl;
    }
    
    public TelaCadastro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        ageField = new javax.swing.JTextField();
        sexField = new javax.swing.JComboBox<>();
        passwordField = new javax.swing.JPasswordField();
        passwordFieldConfirmation = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        occupationField = new javax.swing.JComboBox<>();
        for(Ocupacao o: Ocupacao.values()){

            occupationField.addItem(o.toString());

        }
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoView - Cadastro de Usuários");
        setMinimumSize(new java.awt.Dimension(341, 501));
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(90, 142, 185));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel6FocusGained(evt);
            }
        });
        jPanel6.setLayout(null);

        ageField.setName("idade"); // NOI18N
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        jPanel6.add(ageField);
        ageField.setBounds(70, 50, 80, 23);
        ageField.getAccessibleContext().setAccessibleName("ageField");

        sexField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        sexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexFieldActionPerformed(evt);
            }
        });
        jPanel6.add(sexField);
        sexField.setBounds(210, 50, 50, 20);
        sexField.getAccessibleContext().setAccessibleName("sexField");

        jPanel6.add(passwordField);
        passwordField.setBounds(110, 110, 150, 20);
        jPanel6.add(passwordFieldConfirmation);
        passwordFieldConfirmation.setBounds(110, 140, 150, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Cadastre-me agora!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(100, 180, 160, 30);

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(20, 180, 70, 30);

        occupationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationFieldActionPerformed(evt);
            }
        });
        jPanel6.add(occupationField);
        occupationField.setBounds(110, 80, 150, 20);
        occupationField.getAccessibleContext().setAccessibleName("ocupationField");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Idade:");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(20, 50, 88, 20);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ocupação:");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(20, 80, 88, 20);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Sexo:");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(160, 50, 88, 19);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Senha:");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(20, 110, 120, 17);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Confirme-a:");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(20, 140, 88, 17);

        jPanel8.setBackground(new java.awt.Color(33, 73, 113));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Entre com as suas informações:");
        jPanel8.add(jLabel18);
        jLabel18.setBounds(10, 0, 220, 30);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(20, 0, 240, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(30, 140, 280, 230);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Aqui você poderá se tornar um Moviewer!");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 100, 300, 20);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Moview-Logo.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(-10, 10, 350, 80);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BGLogin.gif"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 340, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.tl.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        if (ageField.getText().isEmpty()==false && passwordField.getText().isEmpty()==false && passwordFieldConfirmation.getText().isEmpty()==false)  {
            if (passwordField.getText().equals(passwordFieldConfirmation.getText())) {
                if (passwordField.getText().length()>=3) {
                
                    Arquivo arq = new Arquivo();
                    ArrayList<Usuario> u = arq.leArquivoUsuario();
                    int ultimoN = u.get(u.size()-1).getIdUsuario();
                    Usuario usuario = new Usuario(ultimoN + 1, Integer.parseInt(ageField.getText()), sexField.getSelectedItem().toString().charAt(0), Ocupacao.valueOf(occupationField.getSelectedItem().toString()), passwordFieldConfirmation.getText(), false);
                    Arquivo.adicionaNoArquivoUser(usuario);
                    JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso! Seu iD de usuário é: "+usuario.getIdUsuario()+". Você agora é oficialmente um MoViewer!");
                    this.dispose();
                    this.tl.show();
                } else {
                    JOptionPane.showMessageDialog(this, "Sua senha deve ter no mínimo 3 caracteres!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "As senhas inseridas não conferem!");
            }
        } else {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de prosseguir!");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void occupationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationFieldActionPerformed

    private void jPanel6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel6FocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jPanel6FocusGained

    private void sexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JComboBox<String> occupationField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordFieldConfirmation;
    private javax.swing.JComboBox<String> sexField;
    // End of variables declaration//GEN-END:variables
}
