/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author seccim
 */
public class TelaAdmin extends javax.swing.JFrame {

    private ArrayList<Usuario> usuarios;
    private Administrador admin;
    
    public void copiaUsuario(ArrayList<Usuario> u, Administrador ad) {
        this.usuarios = u;
        this.admin = ad;
        this.setTitle("MoView - Administrador "+this.admin.getNickName());
        for (int i=0;i<this.usuarios.size();i++) {
            if (usuarios.get(i).isAvaliou()==false) {
                usuariosField.addItem(String.valueOf(usuarios.get(i).getIdUsuario()));
            }
        }
    }
    
    /**
     * Creates new form TelaAdmin
     */
    public TelaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        usuariosField = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        occupationField = new javax.swing.JComboBox<>();
        for(Ocupacao o: Ocupacao.values()){

            occupationField.addItem(o.toString());

        }
        ageField = new javax.swing.JTextField();
        sexField = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 497));
        getContentPane().setLayout(null);

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Olá, Administrador MoViewer. Selecione o usário que deseja excluir.");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(10, 90, 410, 24);

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("iD do usuário:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(70, 120, 90, 20);

        usuariosField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o ID" }));
        usuariosField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usuariosFieldItemStateChanged(evt);
            }
        });
        getContentPane().add(usuariosField);
        usuariosField.setBounds(160, 120, 93, 20);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Moview-Logo.png"))); // NOI18N
        getContentPane().add(jLabel30);
        jLabel30.setBounds(0, 10, 340, 80);

        jPanel12.setBackground(new java.awt.Color(33, 73, 113));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Insira sua senha, Adm.:");
        jPanel12.add(jLabel28);
        jLabel28.setBounds(10, -2, 190, 40);
        jPanel12.add(passwordField);
        passwordField.setBounds(150, 10, 100, 20);

        getContentPane().add(jPanel12);
        jPanel12.setBounds(50, 300, 260, 40);

        jPanel11.setBackground(new java.awt.Color(33, 73, 113));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Confirme as informações do usuário antes de prosseguir:");
        jPanel11.add(jLabel24);
        jLabel24.setBounds(10, 0, 310, 30);

        getContentPane().add(jPanel11);
        jPanel11.setBounds(10, 170, 330, 30);

        jPanel7.setBackground(new java.awt.Color(90, 142, 185));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel7FocusGained(evt);
            }
        });
        jPanel7.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Idade:");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(110, 30, 39, 16);

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Sexo:");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(20, 30, 32, 16);

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ocupação:");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(20, 60, 100, 20);

        occupationField.setEnabled(false);
        occupationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationFieldActionPerformed(evt);
            }
        });
        jPanel7.add(occupationField);
        occupationField.setBounds(110, 60, 130, 20);

        ageField.setEnabled(false);
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        jPanel7.add(ageField);
        ageField.setBounds(170, 30, 70, 20);

        sexField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        sexField.setEnabled(false);
        jPanel7.add(sexField);
        sexField.setBounds(60, 30, 33, 23);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(50, 190, 260, 110);

        jButton5.setText("Remover usuário");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(180, 360, 130, 23);

        jButton1.setText("Voltar");
        jButton1.setPreferredSize(new java.awt.Dimension(113, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 360, 61, 23);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BGLogin.gif"))); // NOI18N
        getContentPane().add(jLabel29);
        jLabel29.setBounds(0, -20, 350, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void occupationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationFieldActionPerformed

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void jPanel7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel7FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7FocusGained

    private void usuariosFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usuariosFieldItemStateChanged
        // TODO add your handling code here:
        if (usuariosField.getSelectedIndex()>0) {
            int idUsuario = Integer.parseInt(usuariosField.getSelectedItem().toString());
            int indiceUsuario = Collections.binarySearch(usuarios, new Usuario(idUsuario));
            ageField.setText(String.valueOf(this.usuarios.get(indiceUsuario).getIdade()));
            occupationField.setSelectedIndex(this.usuarios.get(indiceUsuario).getOcupacao().getValor());
            if (this.usuarios.get(indiceUsuario).getSexo()=='F') {
                sexField.setSelectedIndex(0);
            } else {
                sexField.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_usuariosFieldItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (passwordField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo senha em branco!");
        } else if (passwordField.getText().compareTo(this.admin.getSenha())==1) {
            JOptionPane.showMessageDialog(this, "Senha incorreta!");
        } else{
            if (usuariosField.getSelectedIndex()>0) {
                int idUsuario = Integer.parseInt(usuariosField.getSelectedItem().toString());
                int indiceUsuario = Collections.binarySearch(usuarios, new Usuario(idUsuario));
                this.usuarios.remove(indiceUsuario);
                usuariosField.removeItemAt(usuariosField.getSelectedIndex());
                Collections.sort(usuarios);
                try {
                    Arquivo.reescreveArquivoUsuario(usuarios);
                } catch (IOException ex) {
                    Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(rootPane, "Usuário excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Índice de escolha inválido!");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaLogin tl = new TelaLogin();
        tl.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> occupationField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> sexField;
    private javax.swing.JComboBox<String> usuariosField;
    // End of variables declaration//GEN-END:variables
}
