/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class TelaDetalhesFilmeSelecionado extends javax.swing.JFrame {

    /**
     * Creates new form detalhesFilmeSelecionado
     */
    private Usuario usuario;
    private Filme filme;
    private boolean avaliouEsteFilme;
    private int indiceUsuarioFilme;
    private TelaPrincipal tp;
    
    public void setTelaPrincipal (TelaPrincipal tp) {
        this.tp = tp;
    }

    public int getIndiceUsuarioFilme() {
        return indiceUsuarioFilme;
    }

    public void setIndiceUsuarioFilme(int indiceUsuarioFilme) {
        this.indiceUsuarioFilme = indiceUsuarioFilme;
    }

    public boolean isAvaliouEsteFilme() {
        return avaliouEsteFilme;
    }

    public void setAvaliouEsteFilme(boolean avaliouEsteFilme) {
        this.avaliouEsteFilme = avaliouEsteFilme;
    }
    
    public void setUsuario (Usuario u) {
        this.usuario = u;
    }
    
    
    
    private void setFilme (Filme f) {
        this.filme = f;
        this.setTitle("MovieView - Filme: "+this.filme.getTitulo());
    }
    
    public void setClassificação (int n) {
        switch (n) {
            case 0:
                break;
            case 1:
                this.rb1.setSelected(true);
                break;
            case 2:
                this.rb2.setSelected(true);
                break;
            case 3:
                this.rb3.setSelected(true);
                break;
            case 4:
                this.rb4.setSelected(true);
                break;
            case 5:
                this.rb5.setSelected(true);
                break;
        }
        
    }
    
    
    public void construirDetalhes (Filme f) {
        this.setFilme(f);
        this.nomeFilme.setText(f.getTitulo());
        this.dataFilme.setText(f.getDataLancamento());
        this.imdbFilme.setText(f.getUrlIMDB());
        for (Genero g:f.getGeneros()) {
            this.generoFilme.addItem(g.toString());
        }
        
        Arquivo arq = new Arquivo();
        ArrayList<UsuarioFilme> uf = arq.lerArquivoUsuarioFilme();
        
        if (this.usuario.isAvaliou()==true) {
                
                this.setAvaliouEsteFilme(false);
                for (int i=0;i<uf.size();i++) {
                    if (uf.get(i).getUsuario().getIdUsuario()==this.usuario.getIdUsuario() && uf.get(i).getFilme().getIdFilme()==this.filme.getIdFilme()) {
                        this.setIndiceUsuarioFilme(i);
                        this.setAvaliouEsteFilme(true);
                        this.setClassificação(uf.get(this.getIndiceUsuarioFilme()).getNota());
                        break;
                    }
                }
        }
        
        for (UsuarioFilme u:uf) {
            if (u.getFilme().getIdFilme()==f.getIdFilme()) {
                this.usuarioFilme.addItem(String.valueOf(u.getUsuario().getIdUsuario()));
            }
        }
    }
    
    public TelaDetalhesFilmeSelecionado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        usuarioFilme = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        generoFilme = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        imdbFilme = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        dataFilme = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        nomeFilme = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel1E = new javax.swing.JLabel();
        jLabel2E = new javax.swing.JLabel();
        jLabel3E = new javax.swing.JLabel();
        jLabel4E = new javax.swing.JLabel();
        jLabel5E = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(730, 397));
        getContentPane().setLayout(null);

        jPanel18.setBackground(new java.awt.Color(90, 142, 185));
        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel18FocusGained(evt);
            }
        });
        jPanel18.setLayout(null);

        usuarioFilme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veja quem assistiu" }));
        usuarioFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioFilmeActionPerformed(evt);
            }
        });
        jPanel18.add(usuarioFilme);
        usuarioFilme.setBounds(170, 100, 120, 20);

        jLabel54.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Usuários que já assistiram:");
        jPanel18.add(jLabel54);
        jLabel54.setBounds(10, 100, 149, 20);

        jPanel18.add(generoFilme);
        generoFilme.setBounds(390, 40, 109, 20);

        jLabel53.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Tags (Gênero):");
        jPanel18.add(jLabel53);
        jLabel53.setBounds(290, 40, 88, 20);

        imdbFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imdbFilmeMouseClicked(evt);
            }
        });
        jPanel18.add(imdbFilme);
        imdbFilme.setBounds(50, 70, 450, 23);

        jLabel52.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("IMDB:");
        jPanel18.add(jLabel52);
        jLabel52.setBounds(10, 70, 33, 20);

        dataFilme.setEnabled(false);
        jPanel18.add(dataFilme);
        dataFilme.setBounds(140, 40, 140, 23);

        jLabel51.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Data de lançamento:");
        jPanel18.add(jLabel51);
        jLabel51.setBounds(10, 40, 123, 20);

        nomeFilme.setEnabled(false);
        nomeFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFilmeActionPerformed(evt);
            }
        });
        jPanel18.add(nomeFilme);
        nomeFilme.setBounds(60, 10, 440, 23);

        jLabel50.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Título:");
        jPanel18.add(jLabel50);
        jLabel50.setBounds(10, 10, 33, 16);

        jButton2.setText("Já assisti o filme!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton2);
        jButton2.setBounds(310, 100, 190, 20);

        getContentPane().add(jPanel18);
        jPanel18.setBounds(100, 110, 510, 130);

        jPanel19.setBackground(new java.awt.Color(33, 73, 113));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setLayout(null);

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Filme selecionado em mais detalhes");
        jPanel19.add(jLabel48);
        jLabel48.setBounds(150, -10, 257, 40);

        getContentPane().add(jPanel19);
        jPanel19.setBounds(100, 90, 510, 30);

        jPanel21.setBackground(new java.awt.Color(33, 73, 113));
        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setLayout(null);

        jLabel55.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Já assistiu? Nós adoraríamos saber o que achou do filme. Deixe aqui a sua classificação. Quantos diamantes?");
        jPanel21.add(jLabel55);
        jLabel55.setBounds(10, 0, 650, 20);

        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        jPanel21.add(rb1);
        rb1.setBounds(10, 30, 20, 21);

        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        jPanel21.add(rb3);
        rb3.setBounds(220, 30, 21, 21);

        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });
        jPanel21.add(rb4);
        rb4.setBounds(370, 30, 21, 21);

        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });
        jPanel21.add(rb5);
        rb5.setBounds(520, 30, 21, 21);

        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jPanel21.add(rb2);
        rb2.setBounds(110, 30, 21, 21);

        jLabel1E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/1Estrela.png"))); // NOI18N
        jPanel21.add(jLabel1E);
        jLabel1E.setBounds(30, 30, 110, 22);

        jLabel2E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/2Estrelas.png"))); // NOI18N
        jPanel21.add(jLabel2E);
        jLabel2E.setBounds(140, 30, 50, 22);

        jLabel3E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/3Estrelas.png"))); // NOI18N
        jPanel21.add(jLabel3E);
        jLabel3E.setBounds(250, 30, 80, 22);

        jLabel4E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/4Estrelas.png"))); // NOI18N
        jPanel21.add(jLabel4E);
        jLabel4E.setBounds(400, 30, 110, 22);

        jLabel5E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/5Estrelas.png"))); // NOI18N
        jPanel21.add(jLabel5E);
        jLabel5E.setBounds(550, 30, 110, 22);

        getContentPane().add(jPanel21);
        jPanel21.setBounds(20, 240, 670, 60);

        jButton8.setText("Voltar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 310, 60, 30);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Moview-Logo.png"))); // NOI18N
        getContentPane().add(jLabel57);
        jLabel57.setBounds(150, 0, 490, 90);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BGLarge.gif"))); // NOI18N
        getContentPane().add(jLabel56);
        jLabel56.setBounds(-70, -80, 820, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFilmeActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
        // TODO add your handling code here:
        rb1.setSelected(false);
        rb3.setSelected(false);
        rb2.setSelected(false);
        rb5.setSelected(false);
    }//GEN-LAST:event_rb4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (rb1.isSelected()==false && rb2.isSelected()==false && rb3.isSelected()==false && rb4.isSelected()==false && rb5.isSelected()==false) {
            JOptionPane.showMessageDialog(rootPane, "Você deve avaliar o filme clicando em um dos diamantes!");
        } else {
            Arquivo arq = new Arquivo();
            ArrayList<Usuario> usuariosAuxiliares = arq.leArquivoUsuario();
            UsuarioFilme uf = new UsuarioFilme();
            uf.setUsuario(this.usuario);
            Calendar c = Calendar.getInstance();
            uf.setData(c);
            uf.setFilme(this.filme);
            if (rb1.isSelected()) {
                uf.setNota(1);
            } else if (rb2.isSelected()) {
                uf.setNota(2);
            } else if (rb3.isSelected()) {
                uf.setNota(3);
            } else if (rb4.isSelected()) {
                uf.setNota(4);
            } else if (rb5.isSelected()) {
                uf.setNota(5);
            }
            
            if (this.usuario.isAvaliou()==false || this.avaliouEsteFilme==false) {
                
                if (this.usuario.isAvaliou()==false) {
                    int indice = Collections.binarySearch(usuariosAuxiliares, usuario);
                    usuariosAuxiliares.get(indice).setAvaliou(true);
                }
                
                try {
                    Arquivo.reescreveArquivoUsuario(usuariosAuxiliares);
                } catch (IOException e) {
                    System.err.println("Arquivo não encontrado!");
                }
                Arquivo.adcionaNoArquivoUsuarioFilme(uf);
            } else if (this.avaliouEsteFilme==true) {
                ArrayList<UsuarioFilme> registrosUsuariosFilmes = arq.lerArquivoUsuarioFilme();
                registrosUsuariosFilmes.set(this.getIndiceUsuarioFilme(), uf);
                try {
                    Arquivo.reescreveArquivoUsuarioFilme(registrosUsuariosFilmes);
                } catch (IOException ex) {
                    Logger.getLogger(TelaDetalhesFilmeSelecionado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            JOptionPane.showMessageDialog(rootPane, "Obrigado por sua avaliação!");
            this.tp.zerar();
            this.dispose();
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
        rb2.setSelected(false);
        rb3.setSelected(false);
        rb4.setSelected(false);
        rb5.setSelected(false);
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
        rb1.setSelected(false);
        rb3.setSelected(false);
        rb4.setSelected(false);
        rb5.setSelected(false);
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        // TODO add your handling code here:
        rb1.setSelected(false);
        rb2.setSelected(false);
        rb4.setSelected(false);
        rb5.setSelected(false);
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
        // TODO add your handling code here:
        rb1.setSelected(false);
        rb2.setSelected(false);
        rb4.setSelected(false);
        rb3.setSelected(false);
    }//GEN-LAST:event_rb5ActionPerformed

    private void imdbFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imdbFilmeMouseClicked
        // TODO add your handling code here:
         try {  
            Runtime.getRuntime().exec("cmd.exe /C start "  
                    + this.filme.getUrlIMDB());  
        } catch (IOException ex) {  
           System.out.println(ex.getMessage());  
        }  

    }//GEN-LAST:event_imdbFilmeMouseClicked

    private void jPanel18FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel18FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel18FocusGained

    private void usuarioFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioFilmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
         jLabel48if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhesFilmeSelecionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhesFilmeSelecionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhesFilmeSelecionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhesFilmeSelecionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDetalhesFilmeSelecionado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataFilme;
    private javax.swing.JComboBox<String> generoFilme;
    private javax.swing.JTextField imdbFilme;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1E;
    private javax.swing.JLabel jLabel2E;
    private javax.swing.JLabel jLabel3E;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel4E;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel5E;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JTextField nomeFilme;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JComboBox<String> usuarioFilme;
    // End of variables declaration//GEN-END:variables
}
