/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Júlia
 */
public class TelaRedefinirCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaRedefinirCadastro
     */
    
    private Usuario usuario;
    private TelaPrincipal tp;
    
    public void setUsuario (Usuario u) {
        this.usuario = u;
    }
    
    public void setTelaPrincipal (TelaPrincipal tp) {
        this.tp = tp;
    }
    
    public TelaRedefinirCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel40 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordField2 = new javax.swing.JPasswordField();
        jLabel34 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        ageField1 = new javax.swing.JTextField();
        sexField1 = new javax.swing.JComboBox<>();
        occupationField = new javax.swing.JComboBox<>();
        for(Ocupacao o: Ocupacao.values()){

            occupationField.addItem(o.toString());

        }
        jLabel47 = new javax.swing.JLabel();
        senhaAtualField = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoView - Redefinir Cadastro");
        setMinimumSize(new java.awt.Dimension(401, 503));
        getContentPane().setLayout(null);

        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Seu iD de usuário não poderá ser alterado.");
        jLabel40.setToolTipText("");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(60, 110, 260, 16);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Moview-Logo.png"))); // NOI18N
        getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 330, 90);

        jPanel15.setBackground(new java.awt.Color(33, 73, 113));
        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(null);

        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Redefinição de senha");
        jPanel15.add(jLabel36);
        jLabel36.setBounds(60, 0, 140, 30);

        getContentPane().add(jPanel15);
        jPanel15.setBounds(50, 250, 260, 30);

        jPanel14.setBackground(new java.awt.Color(33, 73, 113));
        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Redefinição de informações pessoais");
        jPanel14.add(jLabel35);
        jLabel35.setBounds(20, 0, 230, 30);

        getContentPane().add(jPanel14);
        jPanel14.setBounds(50, 140, 260, 30);

        jPanel17.setBackground(new java.awt.Color(90, 142, 185));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel17FocusGained(evt);
            }
        });
        jPanel17.setLayout(null);

        jLabel44.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Nova senha:");
        jPanel17.add(jLabel44);
        jLabel44.setBounds(20, 10, 100, 20);

        jLabel45.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Confirme-a:");
        jPanel17.add(jLabel45);
        jLabel45.setBounds(20, 40, 100, 20);

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanel17.add(passwordField);
        passwordField.setBounds(110, 40, 130, 20);

        passwordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField2ActionPerformed(evt);
            }
        });
        jPanel17.add(passwordField2);
        passwordField2.setBounds(110, 10, 130, 20);

        getContentPane().add(jPanel17);
        jPanel17.setBounds(50, 280, 260, 80);

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Hora de alterar seus dados? Vamos lá!");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(60, 90, 260, 16);

        jPanel16.setBackground(new java.awt.Color(90, 142, 185));
        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel16FocusGained(evt);
            }
        });
        jPanel16.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Idade:");
        jPanel16.add(jLabel41);
        jLabel41.setBounds(120, 10, 39, 16);

        jLabel42.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Sexo:");
        jPanel16.add(jLabel42);
        jLabel42.setBounds(20, 10, 32, 16);

        jLabel43.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Ocupação:");
        jPanel16.add(jLabel43);
        jLabel43.setBounds(20, 40, 100, 20);

        ageField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageField1ActionPerformed(evt);
            }
        });
        jPanel16.add(ageField1);
        ageField1.setBounds(170, 10, 70, 20);

        sexField1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        jPanel16.add(sexField1);
        sexField1.setBounds(70, 10, 33, 20);

        occupationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationFieldActionPerformed(evt);
            }
        });
        jPanel16.add(occupationField);
        occupationField.setBounds(110, 40, 130, 20);

        getContentPane().add(jPanel16);
        jPanel16.setBounds(50, 170, 260, 80);

        jLabel47.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Insira sua senha atual:");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(50, 370, 140, 20);

        senhaAtualField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaAtualFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaAtualField);
        senhaAtualField.setBounds(190, 370, 120, 20);

        jButton6.setText("Voltar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(50, 410, 70, 30);

        jButton7.setText("Salvar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(240, 410, 70, 30);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BGLogin.gif"))); // NOI18N
        getContentPane().add(jLabel32);
        jLabel32.setBounds(0, 0, 400, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel17FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel17FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel17FocusGained

    private void ageField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageField1ActionPerformed

    private void jPanel16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel16FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16FocusGained

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField2ActionPerformed

    private void senhaAtualFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaAtualFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaAtualFieldActionPerformed

    private void occupationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationFieldActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (!this.ageField1.getText().isEmpty() && !this.passwordField.getText().isEmpty() && !this.passwordField2.getText().isEmpty() && !this.senhaAtualField.getText().isEmpty()) { 
            if (this.passwordField.getText().equals(this.passwordField2.getText())) {
                if (this.usuario.getSenha().equals(this.senhaAtualField.getText())) {
                    
                    this.usuario.setIdade(Integer.parseInt(this.ageField1.getText()));
                    this.usuario.setSexo(this.sexField1.getSelectedItem().toString().charAt(0));
                    this.usuario.setOcupacao(Ocupacao.valueOf(this.occupationField.getSelectedItem().toString()));
                    this.usuario.setSenha(this.passwordField2.getText());
                    
                    Arquivo arq = new Arquivo();
                    ArrayList<Usuario> u = arq.leArquivoUsuario();
                    
                    int indiceUsuario = Collections.binarySearch(u, this.usuario);
                    u.set(indiceUsuario, usuario);
                    
                    try {
                        Arquivo.reescreveArquivoUsuario(u);
                    } catch (IOException ex) {
                        Logger.getLogger(TelaRedefinirCadastro.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    JOptionPane.showMessageDialog(rootPane, "Seus dados foram alterados com sucesso!");
                    TelaLogin tl = new TelaLogin();
                    this.dispose();
                    tl.show();
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "A senha atual está incorreta!");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Novas senhas não conferem!");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.tp.show();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRedefinirCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRedefinirCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRedefinirCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRedefinirCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRedefinirCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JComboBox<String> occupationField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JPasswordField senhaAtualField;
    private javax.swing.JComboBox<String> sexField1;
    // End of variables declaration//GEN-END:variables
}
