/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Júlia
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    private Usuario usuario;
    private TelaLogin tl;
    private ArrayList<Filme> melhoresFilmes;
    private ArrayList<Filme> filme;
    private ArrayList<Filme> filmesAssistidos;
    private ArrayList<Filme> filmesRecomendados;
     
    public void zerar () {
        Arquivo arq = new Arquivo();
        this.filmesAssistidos = arq.exibeListaDeFilmesAssistida(this.usuario);
        this.constrirTabelaFilmesAssistidos(this.filmesAssistidos);
        this.filme = null;
        this.melhoresFilmes = null;
    }
    
    public void setTelaLogin (TelaLogin tl) {
        this.tl = tl;
    }
    
    public void setUsuario (Usuario u) {
        this.usuario = u;
    }
    
    public void labelidUsario (String s) {
        this.idUsuarioLogado.setText("Bem vindo "+s+". Aqui está a lista de filmes que você já assistiu!");
    }   
     
     public void constrirTabelaFilmesAssistidos(ArrayList<Filme> filmesAssistidos) {
         this.filmesAssistidos = filmesAssistidos;
         Collections.sort(this.filmesAssistidos);
         DefaultTableModel modelo = new DefaultTableModel();  
         this.tabelaFilmesAssistidos.setModel(modelo);
         modelo.addColumn("Número");
         modelo.addColumn("Título");
         modelo.addColumn("Data de Lançamento");
         for (int i=0;i<this.filmesAssistidos.size();i++) {
             modelo.addRow(new Object[]{this.filmesAssistidos.get(i).getIdFilme(), this.filmesAssistidos.get(i).getTitulo(), this.filmesAssistidos.get(i).getDataLancamento()});
         }

     }
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        painelTabela = new javax.swing.JTabbedPane();
        jPanel22 = new javax.swing.JPanel();
        idUsuarioLogado = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFilmesAssistidos = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        filtraTitulo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaTodosFilmes = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        filtraGenero = new javax.swing.JComboBox<>();
        for (Genero g:Genero.values()) {
            filtraGenero.addItem(g.toString());
        }
        jLabel67 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jPanel69 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFilmesMaisVotados = new javax.swing.JTable();
        jLabel69 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jPanel70 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaFilmesRecomendados = new javax.swing.JTable();
        jLabel70 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoView - Tela Principal");

        painelTabela.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                painelTabelaStateChanged(evt);
            }
        });

        jPanel22.setLayout(null);
        jPanel22.add(idUsuarioLogado);
        idUsuarioLogado.setBounds(64, 32, 0, 0);

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Moview-Logo.png"))); // NOI18N
        jPanel22.add(jLabel64);
        jLabel64.setBounds(150, 10, 370, 90);

        jPanel67.setBackground(new java.awt.Color(90, 142, 185));
        jPanel67.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel67.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel67FocusGained(evt);
            }
        });
        jPanel67.setLayout(null);

        tabelaFilmesAssistidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaFilmesAssistidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFilmesAssistidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaFilmesAssistidos);

        jPanel67.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 530, 170);

        jPanel22.add(jPanel67);
        jPanel67.setBounds(80, 160, 550, 190);

        jPanel26.setBackground(new java.awt.Color(33, 73, 113));
        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setLayout(null);

        jLabel62.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Se estiver vazia, está na hora de mudar isso! Clique em \"Todos os filmes\" para continuar!");
        jPanel26.add(jLabel62);
        jLabel62.setBounds(20, 20, 540, 30);

        jLabel63.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Bem-vindo, Moviewer! Aqui está a lista de filmes que você já assistiu. ");
        jPanel26.add(jLabel63);
        jLabel63.setBounds(10, 0, 540, 30);

        jPanel22.add(jPanel26);
        jPanel26.setBounds(80, 110, 550, 240);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BGLarge.gif"))); // NOI18N
        jPanel22.add(jLabel61);
        jLabel61.setBounds(-90, -40, 940, 450);

        painelTabela.addTab("Início", jPanel22);

        jPanel23.setLayout(null);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Moview-Logo.png"))); // NOI18N
        jPanel23.add(jLabel68);
        jLabel68.setBounds(150, 10, 370, 90);

        jPanel27.setBackground(new java.awt.Color(33, 73, 113));
        jPanel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel27.setLayout(null);

        jLabel59.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Hora de encontrar o filme que você quer assistir. Escolha-o abaixo!");
        jPanel27.add(jLabel59);
        jLabel59.setBounds(50, 0, 580, 40);

        jPanel68.setBackground(new java.awt.Color(90, 142, 185));
        jPanel68.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel68.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel68FocusGained(evt);
            }
        });
        jPanel68.setLayout(null);

        jLabel58.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Confira a lista de mais de 1682 filmes do MoView!");
        jPanel68.add(jLabel58);
        jLabel58.setBounds(130, -20, 286, 16);
        jPanel68.add(filtraTitulo);
        filtraTitulo.setBounds(150, 10, 370, 20);

        tabelaTodosFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaTodosFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTodosFilmesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaTodosFilmes);

        jPanel68.add(jScrollPane3);
        jScrollPane3.setBounds(150, 40, 460, 140);

        jButton9.setText("Pesquisar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel68.add(jButton9);
        jButton9.setBounds(530, 10, 79, 23);

        jPanel28.setBackground(new java.awt.Color(33, 73, 113));
        jPanel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel28.setLayout(null);

        jLabel60.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Filtrar por gênero:");
        jPanel28.add(jLabel60);
        jLabel60.setBounds(10, 0, 140, 30);

        filtraGenero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtraGeneroItemStateChanged(evt);
            }
        });
        jPanel28.add(filtraGenero);
        filtraGenero.setBounds(10, 30, 130, 20);

        jPanel68.add(jPanel28);
        jPanel28.setBounds(0, 70, 170, 60);

        jLabel67.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Pesquisar filme:");
        jPanel68.add(jLabel67);
        jLabel67.setBounds(30, 10, 110, 20);

        jPanel27.add(jPanel68);
        jPanel68.setBounds(0, 40, 620, 200);

        jPanel23.add(jPanel27);
        jPanel27.setBounds(40, 100, 620, 240);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BGLarge.gif"))); // NOI18N
        jPanel23.add(jLabel66);
        jLabel66.setBounds(-90, -40, 940, 450);

        painelTabela.addTab("Todos os filmes", jPanel23);

        jPanel24.setLayout(null);

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Moview-Logo.png"))); // NOI18N
        jPanel24.add(jLabel71);
        jLabel71.setBounds(150, 10, 340, 90);

        jPanel29.setBackground(new java.awt.Color(33, 73, 113));
        jPanel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel29.setLayout(null);

        jLabel65.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Confira os 10 filmes melhores classificados do Moview!");
        jPanel29.add(jLabel65);
        jLabel65.setBounds(80, 10, 440, 14);

        jPanel69.setBackground(new java.awt.Color(90, 142, 185));
        jPanel69.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel69.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel69FocusGained(evt);
            }
        });
        jPanel69.setLayout(null);

        jLabel73.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Confira a lista de mais de 1682 filmes do MoView!");
        jPanel69.add(jLabel73);
        jLabel73.setBounds(130, -20, 286, 16);

        tabelaFilmesMaisVotados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaFilmesMaisVotados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFilmesMaisVotadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFilmesMaisVotados);

        jPanel69.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 560, 180);

        jPanel29.add(jPanel69);
        jPanel69.setBounds(0, 30, 580, 200);

        jPanel24.add(jPanel29);
        jPanel29.setBounds(60, 110, 580, 230);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BGLarge.gif"))); // NOI18N
        jPanel24.add(jLabel69);
        jLabel69.setBounds(-90, -40, 940, 450);

        painelTabela.addTab("Filmes mais votados", jPanel24);

        jPanel25.setLayout(null);

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Moview-Logo.png"))); // NOI18N
        jPanel25.add(jLabel72);
        jLabel72.setBounds(150, 10, 370, 90);

        jPanel30.setBackground(new java.awt.Color(33, 73, 113));
        jPanel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel30.setLayout(null);

        jLabel74.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Confira aqui quais filmes o Moview recomenda para você!");
        jPanel30.add(jLabel74);
        jLabel74.setBounds(60, 0, 490, 30);

        jPanel70.setBackground(new java.awt.Color(90, 142, 185));
        jPanel70.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel70.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel70FocusGained(evt);
            }
        });
        jPanel70.setLayout(null);

        jLabel75.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Confira a lista de mais de 1682 filmes do MoView!");
        jPanel70.add(jLabel75);
        jLabel75.setBounds(130, -20, 286, 16);

        tabelaFilmesRecomendados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tabelaFilmesRecomendados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFilmesRecomendadosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaFilmesRecomendados);

        jPanel70.add(jScrollPane4);
        jScrollPane4.setBounds(10, 10, 560, 180);

        jPanel30.add(jPanel70);
        jPanel70.setBounds(0, 30, 580, 200);

        jPanel25.add(jPanel30);
        jPanel30.setBounds(60, 110, 580, 230);

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BGLarge.gif"))); // NOI18N
        jPanel25.add(jLabel70);
        jLabel70.setBounds(-90, -40, 940, 450);

        painelTabela.addTab("Filmes Recomendados", jPanel25);

        jMenu1.setText("Opções");

        jMenuItem1.setText("Alterar meus dados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaRedefinirCadastro trc = new TelaRedefinirCadastro();
        trc.setUsuario(this.usuario);
        this.hide();
        trc.setTelaPrincipal(this);
        trc.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JOptionPane.showMessageDialog(rootPane, "Até logo!");
        this.tl.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void painelTabelaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_painelTabelaStateChanged
        // TODO add your handling code here:
        if (this.painelTabela.getSelectedIndex()==2 && this.melhoresFilmes==null) {
            DefaultTableModel modelo = new DefaultTableModel();
            this.tabelaFilmesMaisVotados.setModel(modelo);
            modelo.addColumn("Colocação");
            modelo.addColumn("Número");
            modelo.addColumn("Título");
            modelo.addColumn("Classificação");
            modelo.addColumn("Nº de vezes visto");
            Arquivo arq = new Arquivo();
            this.melhoresFilmes = arq.filmesMaisVotados();
            for (int i=0;i<melhoresFilmes.size();i++) {
                DecimalFormat df = new DecimalFormat("#.0");
                modelo.addRow(new Object[]{(i+1)+"º" , melhoresFilmes.get(i).getIdFilme(), melhoresFilmes.get(i).getTitulo(), df.format(melhoresFilmes.get(i).getNotaFinal()), melhoresFilmes.get(i).getTotalUsuarios()});
            }
            /*this.tabelaFilmesMaisVotados.getColumnModel().getColumn(0).setPreferredWidth(5);
            this.tabelaFilmesMaisVotados.getColumnModel().getColumn(1).setPreferredWidth(5);
            this.tabelaFilmesMaisVotados.getColumnModel().getColumn(2).setPreferredWidth(100);
            this.tabelaFilmesMaisVotados.getColumnModel().getColumn(3).setPreferredWidth(10);
            this.tabelaFilmesMaisVotados.getColumnModel().getColumn(4).setPreferredWidth(10);*/
        }

        if (this.painelTabela.getSelectedIndex()==1 && this.filme==null) {
            DefaultTableModel modelo = new DefaultTableModel();
            this.tabelaTodosFilmes.setModel(modelo);
            modelo.addColumn("Número");
            modelo.addColumn("Título");
            Arquivo arq = new Arquivo();
            this.filme = arq.lerArquivoFilme();
            Collections.sort(this.filme);
        //    int indice=0;
            for (int i=0;i<filme.size();i++) {
          //      indice = Collections.binarySearch(this.filmesAssistidos, this.filme.get(i));
            //    if (this.filmesAssistidos.contains(this.filme.get(i))==false && indice<0) {
                    modelo.addRow(new Object[]{filme.get(i).getIdFilme(), filme.get(i).getTitulo()});
              //  }
            }
        }
        
        if (this.painelTabela.getSelectedIndex()==3) {
            Arquivo arq = new Arquivo();
            this.filmesRecomendados = arq.sugerirFilmes(this.usuario);
            DefaultTableModel dtm = new DefaultTableModel();
            this.tabelaFilmesRecomendados.setModel(dtm);
            dtm.addColumn("Número");
            dtm.addColumn("Título");
            dtm.addColumn("Nota");
            
            if (this.filmesRecomendados!=null) {
                
                Collections.sort(filmesRecomendados, new ComparatorFilme());
                int indice=0;
                for (Filme f:this.filmesRecomendados) {
                    indice = Collections.binarySearch(this.filmesAssistidos, f);
                    if (indice<0) {
                        DecimalFormat df = new DecimalFormat("#.0");
                        dtm.addRow(new Object[]{f.getIdFilme(), f.getTitulo(), df.format(f.getNotaFinal())});
                    }
                }
            } else {
                
                JOptionPane.showMessageDialog(rootPane, "Você não assistiu a nenhum filme! Não é possível recomendar filmes!");
            }
            
        }
    }//GEN-LAST:event_painelTabelaStateChanged

    private void tabelaFilmesMaisVotadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFilmesMaisVotadosMouseClicked
        // TODO add your handling code here:
        if (this.tabelaFilmesMaisVotados.getSelectedRow()>=0) {
            Object o = this.tabelaFilmesMaisVotados.getValueAt(this.tabelaFilmesMaisVotados.getSelectedRow(), 1);
            int s = (int) o;
            //JOptionPane.showMessageDialog(rootPane, s);
            TelaDetalhesFilmeSelecionado dfs = new TelaDetalhesFilmeSelecionado();
            dfs.setUsuario(this.usuario);
            Collections.sort(this.melhoresFilmes);
            int indiceMelhorFilmeSelecionado = Collections.binarySearch(this.melhoresFilmes, new Filme(s));
            dfs.construirDetalhes(this.melhoresFilmes.get(indiceMelhorFilmeSelecionado));
            dfs.setTelaPrincipal(this);
            dfs.show();

        }

    }//GEN-LAST:event_tabelaFilmesMaisVotadosMouseClicked

    private void filtraGeneroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtraGeneroItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        this.tabelaTodosFilmes.setModel(modelo);
        modelo.addColumn("Número");
        modelo.addColumn("Título");
        //int indice=0;
        for (int i=0;i<filme.size();i++) {
          //  indice = Collections.binarySearch(this.filmesAssistidos, this.filme.get(i));
            for (Genero g:filme.get(i).getGeneros()) {
                if (g.getValor()==this.filtraGenero.getSelectedIndex() ) {
                    modelo.addRow(new Object[]{filme.get(i).getIdFilme(), filme.get(i).getTitulo()});
                }
            }
        }
    }//GEN-LAST:event_filtraGeneroItemStateChanged

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (this.filtraTitulo.getText().isEmpty()==false) {
            DefaultTableModel modelo = new DefaultTableModel();
            this.tabelaTodosFilmes.setModel(modelo);
            modelo.addColumn("Número");
            modelo.addColumn("Título");
            //int indice =0;
            for (int i=0;i<filme.size();i++) {
              //  indice = Collections.binarySearch(this.filmesAssistidos, this.filme.get(i));
                if (filme.get(i).getTitulo().toLowerCase().contains(this.filtraTitulo.getText().toLowerCase())) {
                    modelo.addRow(new Object[]{filme.get(i).getIdFilme(), filme.get(i).getTitulo()});
                }

            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tabelaTodosFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTodosFilmesMouseClicked
        // TODO add your handling code here:
        if (this.tabelaTodosFilmes.getSelectedRow()>=0) {
            Object o = this.tabelaTodosFilmes.getValueAt(this.tabelaTodosFilmes.getSelectedRow(), 0);
            int s = (int) o;
            //JOptionPane.showMessageDialog(rootPane, s);
            TelaDetalhesFilmeSelecionado dfs = new TelaDetalhesFilmeSelecionado();
            dfs.setUsuario(this.usuario);
            dfs.construirDetalhes(this.filme.get(s-1));
            dfs.setTelaPrincipal(this);
            dfs.show();
        }
    }//GEN-LAST:event_tabelaTodosFilmesMouseClicked

    private void tabelaFilmesAssistidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFilmesAssistidosMouseClicked
        // TODO add your handling code here:
        if (this.tabelaFilmesAssistidos.getSelectedRow()>=0) {
            Object o = this.tabelaFilmesAssistidos.getValueAt(this.tabelaFilmesAssistidos.getSelectedRow(), 0);
            int s = (int) o;
            //JOptionPane.showMessageDialog(rootPane, s);
            TelaDetalhesFilmeSelecionado dfs = new TelaDetalhesFilmeSelecionado();
            dfs.setUsuario(this.usuario);
            Collections.sort(this.filmesAssistidos);
            int indiceFilmeAssistidoSelecionado = Collections.binarySearch(this.filmesAssistidos, new Filme(s));
            dfs.construirDetalhes(this.filmesAssistidos.get(indiceFilmeAssistidoSelecionado));
            dfs.setTelaPrincipal(this);
            dfs.show();
            
        }

    }//GEN-LAST:event_tabelaFilmesAssistidosMouseClicked

    private void jPanel68FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel68FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel68FocusGained

    private void jPanel67FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel67FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel67FocusGained

    private void jPanel69FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel69FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel69FocusGained

    private void tabelaFilmesRecomendadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFilmesRecomendadosMouseClicked
        // TODO add your handling code here:
         if (this.tabelaFilmesRecomendados.getSelectedRow()>=0) {
            Object o = this.tabelaFilmesRecomendados.getValueAt(this.tabelaFilmesRecomendados.getSelectedRow(), 0);
            int s = (int) o;
            //JOptionPane.showMessageDialog(rootPane, s);
            TelaDetalhesFilmeSelecionado dfs = new TelaDetalhesFilmeSelecionado();
            dfs.setUsuario(this.usuario);
            Collections.sort(this.filmesRecomendados);
            int indiceFilmeAssistidoSelecionado = Collections.binarySearch(this.filmesRecomendados, new Filme(s));
            dfs.construirDetalhes(this.filmesRecomendados.get(indiceFilmeAssistidoSelecionado));
            dfs.setTelaPrincipal(this);
            dfs.show();
            
        }
    }//GEN-LAST:event_tabelaFilmesRecomendadosMouseClicked

    private void jPanel70FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel70FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel70FocusGained

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        JOptionPane.showMessageDialog(this, "Atividade Acadêmica de Computação II - 2015.2 - UFRRJ.\n Feita pelos alunos: Bruno Martins, Júlia Rodrigues e Matheus Abreu.");
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> filtraGenero;
    private javax.swing.JTextField filtraTitulo;
    private javax.swing.JLabel idUsuarioLogado;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane painelTabela;
    private javax.swing.JTable tabelaFilmesAssistidos;
    private javax.swing.JTable tabelaFilmesMaisVotados;
    private javax.swing.JTable tabelaFilmesRecomendados;
    private javax.swing.JTable tabelaTodosFilmes;
    // End of variables declaration//GEN-END:variables
}
